In [22]:
import pandas as pd
df=pd.read_csv("../data/processed/processed_sales.csv")

In [23]:
df.head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,5,5
1,10,2010-02-05,2193048.75,0,54.34,2.962,126.442065,9.765,2010,2,5,5
2,37,2010-02-05,536006.73,0,45.97,2.572,209.852966,8.554,2010,2,5,5
3,17,2010-02-05,789036.02,0,23.11,2.666,126.442065,6.548,2010,2,5,5
4,30,2010-02-05,465108.52,0,39.05,2.572,210.752605,8.324,2010,2,5,5
5,25,2010-02-05,677231.63,0,21.10,2.784,204.247194,8.187,2010,2,5,5
6,22,2010-02-05,1033017.37,0,24.36,2.788,135.352461,8.283,2010,2,5,5
7,23,2010-02-05,1364721.58,0,15.25,2.788,131.527903,5.892,2010,2,5,5
8,24,2010-02-05,1388725.63,0,22.43,2.954,131.527903,8.326,2010,2,5,5
9,19,2010-02-05,1507637.17,0,20.96,2.954,131.527903,8.350,2010,2,5,5

In [24]:
df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151,2010.965035,6.447552,25.818182,15.678322
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885,0.797019,3.238308,14.129201,8.755780
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000,2010.000000,1.000000,1.000000,1.000000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000,2010.000000,4.000000,14.000000,8.000000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000,2011.000000,6.000000,26.000000,16.000000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000,2012.000000,9.000000,38.000000,23.000000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000,2012.000000,12.000000,52.000000,31.000000

step2 sort data by stores and date

In [49]:

df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values(["Store", "Date"])

In [50]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,lag_1,lag_2,lag_4,rolling_mean_4
402,1,2010-04-02,1594968.28,0,62.27,2.719,210.820450,7.808,2010,4,13,2,1404429.92,1472515.79,1554806.68,1.477864e+06
411,1,2010-04-09,1545418.53,0,65.86,2.770,210.622857,7.808,2010,4,14,9,1594968.28,1404429.92,1439541.59,1.504333e+06
451,1,2010-04-16,1466058.28,0,66.32,2.808,210.488700,7.808,2010,4,15,16,1545418.53,1594968.28,1472515.79,1.502719e+06
531,1,2010-04-23,1391256.12,0,64.84,2.795,210.439123,7.808,2010,4,16,23,1466058.28,1545418.53,1404429.92,1.499425e+06
549,1,2010-04-30,1425100.71,0,67.41,2.780,210.389546,7.808,2010,4,17,30,1391256.12,1466058.28,1594968.28,1.456958e+06

CREATE LAG FEATURES( stores about the last sales )

In [51]:
df["lag_1"] = df.groupby("Store")["Weekly_Sales"].shift(1)
df["lag_2"]=df.groupby("Store")["Weekly_Sales"].shift(2)
df["lag_4"]=df.groupby("Store")["Weekly_Sales"].shift(4)

 STEP3 calculate the ROLLING MEANS (BEACAUSE  smooth noise and captures trends)

In [52]:
df["rolling_mean_4"] = (
    df.groupby("Store")["Weekly_Sales"]
      .rolling(4)
      .mean()
      .reset_index(level=0, drop=True)
)

In [53]:
df=df.dropna()

In [54]:
y=df["Weekly_Sales"]

In [55]:
X = df.drop(["Weekly_Sales", "Date"], axis=1)

In [56]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,lag_1,lag_2,lag_4,rolling_mean_4
549,1,2010-04-30,1425100.71,0,67.41,2.780,210.389546,7.808,2010,4,17,30,1391256.12,1466058.28,1594968.28,1.456958e+06
602,1,2010-05-07,1603955.12,0,72.55,2.835,210.339968,7.808,2010,5,18,7,1425100.71,1391256.12,1545418.53,1.471593e+06
668,1,2010-05-14,1494251.50,0,74.78,2.854,210.337426,7.808,2010,5,19,14,1603955.12,1425100.71,1466058.28,1.478641e+06
684,1,2010-05-21,1399662.07,0,76.44,2.826,210.617093,7.808,2010,5,20,21,1494251.50,1603955.12,1391256.12,1.480742e+06
721,1,2010-05-28,1432069.95,0,80.44,2.759,210.896761,7.808,2010,5,21,28,1399662.07,1494251.50,1425100.71,1.482485e+06

In [57]:
X

,Store,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,lag_1,lag_2,lag_4,rolling_mean_4
549,1,0,67.41,2.780,210.389546,7.808,2010,4,17,30,1391256.12,1466058.28,1594968.28,1.456958e+06
602,1,0,72.55,2.835,210.339968,7.808,2010,5,18,7,1425100.71,1391256.12,1545418.53,1.471593e+06
668,1,0,74.78,2.854,210.337426,7.808,2010,5,19,14,1603955.12,1425100.71,1466058.28,1.478641e+06
684,1,0,76.44,2.826,210.617093,7.808,2010,5,20,21,1494251.50,1603955.12,1391256.12,1.480742e+06
721,1,0,80.44,2.759,210.896761,7.808,2010,5,21,28,1399662.07,1494251.50,1425100.71,1.482485e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6254,45,0,64.88,3.997,192.013558,8.684,2012,9,39,28,723086.20,702238.27,734297.87,7.262528e+05
6270,45,0,64.89,3.985,192.170412,8.667,2012,10,40,5,713173.95,723086.20,766512.66,7.179884e+05
6301,45,0,54.47,4.000,192.327265,8.667,2012,10,41,12,733455.07,713173.95,702238.27,7.260449e+05
6354,45,0,56.47,3.969,192.330854,8.667,2012,10,42,19,734464.36,733455.07,723086.20,7.248047e+05
6434,45,0,58.85,3.882,192.308899,8.667,2012,10,43,26,718125.53,734464.36,713173.95,7.365816e+05

In [58]:
y

549     1425100.71
602     1603955.12
668     1494251.50
684     1399662.07
721     1432069.95
           ...
6254     713173.95
6270     733455.07
6301     734464.36
6354     718125.53
6434     760281.43
Name: Weekly_Sales, Length: 5895, dtype: float64

 Train-Test Split (Time-based split)

In [59]:
train = df[df["Date"] < "2012-01-01"]
test = df[df["Date"] >= "2012-01-01"]

In [60]:
X_train = train.drop(["Weekly_Sales", "Date"], axis=1)
y_train = train["Weekly_Sales"]

In [61]:
X_test = test.drop(["Weekly_Sales", "Date"], axis=1)
y_test = test["Weekly_Sales"]

In [65]:
print(df.columns
      )

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment', 'Year', 'Month', 'Week', 'Day',
       'lag_1', 'lag_2', 'lag_4', 'rolling_mean_4'],
      dtype='object')

In [66]:
df.to_csv("../data/processed/feature_engineered_sales.csv", index=False)

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment', 'Year', 'Month', 'Week', 'Day',
       'lag_1', 'lag_2', 'lag_4', 'rolling_mean_4'],
      dtype='object')